### ISSUE TITLE
Workflow of invoices

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/parelpracht-client#19]
The current workflow for invoices is `Created > Sent > Paid`, however, while sending out invoices I have noticed that it might be nice to also have a 'Proposed' options for invoices. (such state already exists for contracts).

Often when you send the originally generated invoice, some changes still have to be done. This includes changing address, adding PO numbers or even changing the term of an invoice. This process includes sending the invoice, but you cannot switch so `Sent` yet, as this makes the invoice immutable. For this reason, there is no way to distinguish between an invoice that was just created, and one that has been through some stages of change already.

My proposition would be to change the workflow to `Created > Proposed > Sent > Paid` so it is cleared (and also, easier to filter) what has been discussed about a certain invoice already.

**Comment by Yoronex** [comment]
I am a bit confused, because on parelpracht.test.gewis.nl, invoices do not seem to be immutable. Either I am missing something, or there is a bug somewhere. I still agree that invoices should indeed be immutable though

**Comment by Gijsdeman** [comment]
Then I would opt that as soon as the invoice is sent, that it would be immutable from that point on cause it is at that point that it indeed cannot change anymore. (either way, I think the flow of ‘sent’ is a bit weird, cause if it is send it does not mean that the invoice at that point is final, but that is what you would imply with ‘sent’ cause it is then at the company and should in principle not be able to be changed(?))
