### ISSUE TITLE
Insights broken

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/parelpracht-client#21]
Ik ga nog niet eens proberen te vertalen: holy fuck hier klopt echt geen zak van hahahaha

10000 mismatches aan informatie die op de main page staan van parelpracht. De sommen kloppen voor geen meter en het is onduidelijk welke informatie nu daadwerkelijk correct is en welke informatie dat niet is.

Had van Eline begrepen dat status `invoiced` en `insert jaar` nog los bij elkaar opgeteld meoten worden, maar zelfs dan is het getal wat eruit komt anders dan wat op de homepage staat.

Het is oprecht wel een ding dat dit opgelost moet worden, want het is nu gewoon niet duidelijk welke informatie daadwerkelijk klopt, en welke informatie niet.

**Comment by Yoronex** [comment]
Only the "invoiced" column of the financial overview on the dashboard does not seem to be in line with the insights table. If you click on the "invoiced" financial overview column, you are redirected to the insights table. However, the sum of all rows does not equal the number on the dashboard.

**Comment by Yoronex** [comment]
Duplicate https://github.com/GEWIS/parelpracht-client/issues/30.
