### ISSUE TITLE
Products categories

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/parelpracht-client#22]
Het is handig om maar 5 categorien te hebben zoals op de jaarbegroting, maar ik denk dat subcategorien zoals die nu bestaan nog verkeerd zouden zijn. I.e. onder `digital sponsoring` de subcategorien `social media` en `digital sponsoring` hangen. Zie ook #23 voor andere toegevoegde waarde.

**Comment by Yoronex** [comment]
This is up to the external affairs officer.
