### ISSUE TITLE
LaTeX compilation fails on special characters

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/parelpracht-client#27]
Some companie names or other stuff that is filled out on contracts might contain special characters like %, $ and & which cannot be compiled in LaTeX without being escaped. For this reason, there contract cannot be compiled in ParelPracht.

All information filled out on the contracts is plaintext, and for this reason this text can probably be checked on these characted and escaped before being filled out in the contracts. Pls fix

**Comment by Yoronex** [comment]
Seems to be fixed now, probably in https://github.com/GEWIS/parelpracht-server/pull/16.
