### ISSUE TITLE
Incorrect usage of getDay all over the place

### ISSUE THREAD

**Issue by MaikoCheng** [GEWIS/parelpracht-client#60]
![image](https://github.com/GEWIS/parelpracht-client/assets/71335375/290276f1-52ee-4366-a633-a1a7fd9d0fac)

**Comment by MaikoCheng** [comment]
By the way, month is 0-indexed so it is always off by one month. Everywhere.

**Comment by MaikoCheng** [comment]
I made a pull request for this.

**Comment by MaikoCheng** [comment]
I was not aware how to make a pull request, I did do it now :o

**Comment by Gijsdeman** [comment]
See [#26](https://github.com/GEWIS/parelpracht-server/pull/26).
