### ISSUE TITLE
Insights - suggested not showing all contracts/products

### ISSUE THREAD

**Issue by MaikoCheng** [GEWIS/parelpracht-client#61]
When pressing the suggested button on the landing page, you're taken to the insights which does not include all contracts in the overview (amounts on the bottom are correct)
![image](https://github.com/GEWIS/parelpracht-client/assets/71335375/f8ac6d5b-39af-43c0-95d8-44faeee3082c)
E.g. C1268-C1274 should all be in this category but do not show up here. I have since figured out that it does work when directly pressing "insights" and filtering.

**Comment by Gijsdeman** [comment]
Seems to be a duplicate of #54, so I will close this issue.
