### ISSUE TITLE
Roles Signee and financial not sufficient for treasurer

### ISSUE THREAD

**Issue by Yaneriaf** [GEWIS/parelpracht-client#67]
The roles signee and financial do not allow the treasurer to see details of companies or download invoices. This was discovered after the KCC of last year was discharged.
![image](https://github.com/GEWIS/parelpracht-client/assets/42782248/737e16b7-3b89-451a-a592-23fa804572fd)
![image](https://github.com/GEWIS/parelpracht-client/assets/42782248/67ad73b2-6e2a-4719-8851-6f31f1777ca6)

**Comment by Yaneriaf** [comment]
Invoice page can be viewed, but attachments cannot. Company page is apperently intended behavior, but I would very much like to be able to see it. I get error messages on the home page as well.

**Comment by Yoronex** [comment]
Fixed in https://github.com/GEWIS/parelpracht-client/pull/74. Thanks @gewoonsandor for your help!
